apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cds_ui.name | quote }}
  labels:
{{ include "cds.labels" . | indent 4 }}
    app.name: {{ .Values.cds_ui.name | quote }}
spec:
  replicas: {{ .Values.cds_ui.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cds.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.name: {{ .Values.cds_ui.name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cds.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.name: {{ .Values.cds_ui.name | quote }}
        app: {{ .Values.cds_ui.name | quote }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Values.cds_ui.name | quote }}
          image: "{{ .Values.cds_ui.image.repository }}:{{ include "cds.tag" . }}"
          imagePullPolicy: {{ .Values.cds_ui.image.pullPolicy }}
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: commit.id
              value: {{ .Values.global.commit_id | quote }}
          resources:
            {{- toYaml .Values.cds_ui.resources | nindent 12 }}
      {{- with .Values.cds_ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.cds_ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.cds_ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cds_ui.name | quote }}
  labels:
{{ include "cds.labels" . | indent 4 }}
    app.name: {{ .Values.cds_ui.name | quote }}
spec:
  type: {{ .Values.cds_ui.service.type }}
  ports:
    - name: {{ .Values.cds_ui.name | quote }}
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "cds.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.name: {{ .Values.cds_ui.name | quote }}