apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8888"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  name: java-metric
spec:
  ports:
  - name: default
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    apptype: java
  type: ClusterIP
status:
  loadBalancer: {}
